#!/usr/bin/env bash
# GhostToGhost — create & link a Firebase project (run locally after: firebase login)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROJECT_ID="${1:-ghosttoghost}"
DISPLAY_NAME="${2:-GhostToGhost}"
WEB_APP_NAME="${3:-ghosttoghost-web}"

if ! command -v firebase >/dev/null 2>&1; then
  echo "Firebase CLI not found. Install: npm install -g firebase-tools"
  exit 1
fi

if ! firebase login:list 2>/dev/null | grep -q "@"; then
  echo "Not logged in. Run: firebase login"
  exit 1
fi

echo "→ Checking project ID: $PROJECT_ID"
if firebase projects:list 2>/dev/null | grep -q "$PROJECT_ID"; then
  echo "  Project already exists — linking."
else
  echo "→ Creating Firebase project..."
  firebase projects:create "$PROJECT_ID" --display-name "$DISPLAY_NAME"
fi

echo "→ Writing .firebaserc"
cat > .firebaserc <<EOF
{
  "projects": {
    "default": "$PROJECT_ID"
  }
}
EOF

firebase use "$PROJECT_ID"

echo "→ Registering web app (if needed)..."
APP_ID=""
while IFS= read -r line; do
  if [[ "$line" == *"$WEB_APP_NAME"* ]]; then
    APP_ID="$(echo "$line" | awk '{print $1}')"
    break
  fi
done < <(firebase apps:list WEB --project "$PROJECT_ID" 2>/dev/null || true)

if [[ -z "$APP_ID" ]]; then
  CREATE_OUT="$(firebase apps:create WEB "$WEB_APP_NAME" --project "$PROJECT_ID" 2>&1)"
  echo "$CREATE_OUT"
  APP_ID="$(echo "$CREATE_OUT" | sed -n 's/.*App ID: //p' | head -1)"
fi

if [[ -z "$APP_ID" ]]; then
  echo "Could not determine web App ID. Run:"
  echo "  firebase apps:list WEB --project $PROJECT_ID"
  exit 1
fi

echo "→ Fetching SDK config for $APP_ID"
SDK_JSON="$(firebase apps:sdkconfig WEB "$APP_ID" --project "$PROJECT_ID" --json)"
API_KEY="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.apiKey||'')")"
AUTH_DOMAIN="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.authDomain||'')")"
PROJECT_ID_CFG="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.projectId||'')")"
STORAGE_BUCKET="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.storageBucket||'')")"
MESSAGING_SENDER_ID="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.messagingSenderId||'')")"
APP_ID_CFG="$(echo "$SDK_JSON" | node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8')); console.log(j.sdkConfig.appId||'')")"

ENV_FILE="$ROOT/.env.local"
if [[ -f "$ENV_FILE" ]] && grep -q "NEXT_PUBLIC_FIREBASE_API_KEY=" "$ENV_FILE" 2>/dev/null; then
  echo "→ .env.local already has Firebase keys — skipping overwrite"
else
  echo "→ Writing .env.local"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-firebase.sh — $(date -u +%Y-%m-%d)
NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID_CFG
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$APP_ID_CFG

# App Check — Firebase Console → App Check → reCAPTCHA v3
NEXT_PUBLIC_APPCHECK_RECAPTCHA_SITE_KEY=

# Local dev only — Firebase Console → App Check → Manage debug tokens
NEXT_PUBLIC_APPCHECK_DEBUG_TOKEN=

# Firebase Console → Cloud Messaging → Web Push certificates
NEXT_PUBLIC_FIREBASE_VAPID_KEY=
EOF
  echo "  Wrote $ENV_FILE"
fi

echo ""
echo "✓ Firebase project linked: $PROJECT_ID"
echo ""
echo "Next steps (Firebase Console → https://console.firebase.google.com/project/$PROJECT_ID):"
echo "  1. Build → Authentication → enable Anonymous sign-in"
echo "  2. Build → Firestore → Create database (production mode; rules deploy next)"
echo "  3. Build → Storage → Get started"
echo "  4. Build → App Check → register web app (reCAPTCHA v3)"
echo "  5. Build → Cloud Messaging → Web Push → generate key pair → paste VAPID in .env.local"
echo ""
echo "Then deploy from this repo:"
echo "  firebase deploy --only firestore:rules,firestore:indexes,storage,functions"
echo "  npm run dev"
